openapi: 3.0.0
info:
  title: REST API Architecture Example
  version: 1.0.0
  description: Example API with clients resource
servers:
  - url: http://localhost:3000/api/v1
paths:
  /clients:
    get:
      summary: Get all clients
      responses:
        '200':
          description: A list of clients
    post:
      summary: Create a new client
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
      responses:
        '201':
          description: Client created
  /clients/{id}:
    get:
      summary: Get client by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Client found
        '404':
          description: Client not found
    put:
      summary: Update client by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
      responses:
        '200':
          description: Client updated
        '404':
          description: Client not found
    delete:
      summary: Delete client by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Client deleted
        '404':
          description: Client not found